### PR TITLE
Bug fix in entropy filter MPI graph.

### PR DESCRIPTION
**Pull request by tarikdzanic**

### CODE REVIEW

**Comment by FreddieWitherden** [comment]
Add on line 14 as:
```
g1.add_mpi_reqs(m['scal_fpts_recv'] + m['ent_fpts_recv'])
```
(We want to start recv requests as soon as possible .)

**Comment by FreddieWitherden** [comment]
Can also move the request on L103 up (although this is just stylistic).

**Comment by FreddieWitherden** [comment]
Also, this looks just to be for `baseadvec` but were we not also having problems with Navier–Stokes (which is `baseadvecdiff`)?

**Comment by tarikdzanic** [comment]
> Also, this looks just to be for `baseadvec` but were we not also having problems with Navier–Stokes (which is `baseadvecdiff`)?

The issue was only on the preproc graphs which baseadvecdiff inherits from baseadvec

**Pull request merged**
