### PR TITLE
Fix basename for incompressible cylinder 2D example

### PR DESCRIPTION
**Pull request by wigging**

### CODE REVIEW

**Comment by FreddieWitherden** [comment]
Looks good.  Thank you for this.

One slight thing, would you be able to amend the commit to have a . at the end?

**Comment by wigging** [comment]
@FreddieWitherden I'm not sure what you mean by "have a . at the end". Can you elaborate please?

**Comment by wigging** [comment]
Oh, are you referring to the commit message itself?

**Comment by FreddieWitherden** [comment]
> Oh, are you referring to the commit message itself?

Yes, sorry, should have been clearer.

Otherwise if you can fix that and squish/rebase into a single commit we should be ready to go.

**Comment by wigging** [comment]
I made the fix to the commit message. You can choose to "Squash and merge" or "Rebase and merge" using the down arrow next to the "Merge pull request" button on GitHub.

**Pull request merged**
